name: LuckyBit

on:
  workflow_dispatch:
    inputs:
      user:
        description: "Trigger User"
        required: false
        default: me
  schedule:
    # Run 5th Minute of Every Hour
    - cron:  '5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check Luck
      env: 
        USER: ${{ inputs.user }}
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        python LuckyBit.py
